% Aplicacao que permite escolher qual o classificador usar
function choice = app()

    d = dialog('Position',[300 300 400 150],'Name','Choose one option','WindowStyle','normal');
    txt = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[20 80 350 40],...
           'String','Select the training method');
       
    popup = uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[75 70 250 25],...
           'String',{'';'Hardlim';'Hardlim + AM';'Logsig';'Logsig + AM';'Purelin';'Purelin + AM'},...
           'Callback',@popup_callback);
       
    btn = uicontrol('Parent',d,...
           'Position',[150 20 100 25],...
           'String','Close',...
           'Callback','delete(gcf)');
   
    uiwait(d);
   
       function popup_callback(popup,event)
          idx = popup.Value;
          popup_items = popup.String;
          choice = char(popup_items(idx,:));
          uiwait(d);
          
       end
end

